version: "3.8"

services:
  database:
    container_name: database
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASS} 
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - 5435:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:

